config/routes.rb
Rails.application.routes.draw do
  resources :ts_results
  resources :ts_tbls
  devise_for :users
  
  root to: "pages#home"
  
  get "home", to: "pages#home"
  get "about", to: "pages#about"
  get "how_to_use", to: "pages#how_to_use"
  

  
end

app/models/ts_tbl.rb
class TsTbl < ActiveRecord::Base
  belongs_to :user
  has_many :ts_result
  has_attached_file :ts,
                    :path => ':rails_root/public/ts/:id',
                    :url => '/ts/:id'
                    
  do_not_validate_attachment_file_type :ts
end

app/controllers/ts_tbls_controller.rb
class TsTblsController < ApplicationController
  before_action :set_ts_tbl, only: [:show, :update, :destroy, :get_serie_array]
  before_action :authenticate_user!

  # GET /ts_tbls
  # GET /ts_tbls.json
  def index
    @ts_tbls = TsTbl.where("user_id = #{current_user.id}")
  end
####################################################################################
  # GET /ts_tbls/1
  # GET /ts_tbls/1.json
  def show
    @ts_results = TsResult.where("ts_tbl_id = #{params[:id]}")
    @Serie = get_serie_array
    @gon = gon
  end
####################################################################################
  # GET /ts_tbls/new
  def new
    @ts_tbl = TsTbl.new
  end

####################################################################################
  # POST /ts_tbls
  # POST /ts_tbls.json
  def create
      
    @ts_tbl = TsTbl.new(ts_tbl_params)
    @ts_tbl.user_id = current_user.id

    #render :text => ts_tbl_params
    
    respond_to do |format|
      if @ts_tbl.save
        format.html { redirect_to @ts_tbl, notice: 'Ts tbl was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

####################################################################################
  # DELETE /ts_tbls/1
  # DELETE /ts_tbls/1.json
  def destroy
    @ts_tbl.destroy
    respond_to do |format|
      format.html { redirect_to ts_tbls_url, notice: 'Ts tbl was successfully destroyed.' }

    end
  end

    def get_serie_array
        require 'scanf'
        
        serie = []
        File.readlines(@ts_tbl.ts.path).map do |line|
            serie << line.scanf('"%d" %f')
        end
        
        return serie

    end

####################################################################################
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ts_tbl
      @ts_tbl = TsTbl.find(params[:id])
    end
    
####################################################################################
    # Never trust parameters from the scary internet, only allow the white list through.
    def ts_tbl_params
      params.require(:ts_tbl).permit(:ts)
    end
end

app/helpers/ts_tbls_helper.rb
module TsTblsHelper
end

app/views/ts_tbls/_form.html.erb
<%= form_for(@ts_tbl, :html => { :multipart => true }) do |f| %>
  <% if @ts_tbl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ts_tbl.errors.count, "error") %> prohibited this ts_tbl from being saved:</h2>

      <ul>
      <% @ts_tbl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Série Temporal" %>
    <%= f.file_field :ts %>
  </div>
  <div class="actions">
    <%= f.submit "Upload" %>
  </div>
<% end %>

app/views/ts_tbls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Minhas Séries</h1>

<table class="table table-hove" >
  <thead>
    <tr>
      <th>Caminho da Série</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ts_tbls.each do |ts_tbl| %>
      <tr>
        <td><%= link_to "#{ts_tbl.ts.url}" , ts_tbl.ts.url %></td>
        <td><%= link_to 'Mostrar', ts_tbl %></td>
        <td><%= link_to 'Excluir', ts_tbl, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="text-right">
    <%= link_to 'Adicionar uma Série', new_ts_tbl_path %>
</p>

app/views/ts_tbls/new.html.erb
<h1>Upload de Série Temporal</h1>

<%= render 'form' %>

<%= link_to 'Voltar', ts_tbls_path %>

app/views/ts_tbls/show.html.erb
<p>
    <strong>Série Temporal</strong>
    
    <% data = [{name: "Time Serie", data: @Serie.reject {|x| x.empty?}}] %>

    <div id="serie_plot">
        <%= line_chart data ,discrete: true , library: {curveType: "none", pointSize: 0} %>
    </div>
    
</p>

<p>
    <b>
        Histórico de Chamada do Algoritmo
    </b>
</p>

<table class="table table-hover">
    <tr>
        <thead>
            <strong>
                <td>ID</td>
                <td>Motif Size </td>
                <td>Limear</td>
                <td>Normalização</td>
                <td>Algoritmo</td>
                <td>Status</td>
                <td>Mostrar</td>
                <td>Deletar</td>
            </strong>
        </thead>
    </tr>
    <% @ts_results.each do |ts_result| %>
        <tr>
            <td><%= ts_result.id %></td>
            <td><%= ts_result.motif_size %></td>
            <td><%= ts_result.limear %> </td>
            <td><%= ts_result.normalize %></td>
            <td><%= ts_result.algorithm %></td>
            <% result_path = "#{ts_result.ts_tbl.ts.path}.#{ts_result.limear}.#{ts_result.motif_size}.#{ts_result.normalize}.results" %>
        <% if File.exist?(result_path) %>
            <% result_path = "#{ts_result.ts_tbl.ts.url}.#{ts_result.limear}.#{ts_result.motif_size}.#{ts_result.normalize}.results" %>
            <td><i class="icon-ok"></i></td>
            <% else %>
                <td><i class="icon-remove"></i></td>
            <% end %>

            <td><%= link_to ts_result, action: "show" , class:"btn btn-default" do %>
                <i class="icon-eye-open"></i>
                <% end %>
            </td>

            <td><%= link_to  ts_result, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default" do %>
                    <i class="icon-trash"></i>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>


    <div class="btn-group text-right">
        <p class="text-right">
            <%= link_to 'Chamar Algoritmo', new_ts_result_path(@ts_tbl), class:"btn btn-default" %>

            <%= link_to 'Voltar', ts_tbls_path, class:"btn btn-default"%>
        </p>
    </div>